# Generated by Django 3.2.8 on 2022-03-14 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(default=' ', max_length=200)),
                ('lead', models.CharField(default=' ', max_length=1000)),
                ('texto', models.CharField(default='SOME ', max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('redactor', models.CharField(default='Tomás Salgado', max_length=200)),
                ('tituloDestacado', models.CharField(default=' ', max_length=100)),
                ('destacado', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('profesion', models.CharField(default='profesor', max_length=100)),
                ('ciclo', models.IntegerField(default=3)),
                ('universidad', models.CharField(default='-', max_length=100)),
                ('correo', models.CharField(default='sin correo', max_length=200)),
                ('foto', models.ImageField(upload_to='profesores')),
            ],
        ),
    ]
