# Generated by Django 3.2.8 on 2022-03-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.noticia')),
            ],
        ),
    ]
