# Generated by Django 3.2.8 on 2022-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_imagesnoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
    ]
