# Generated by Django 3.2.8 on 2022-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alergico',
            field=models.CharField(default='no es alergico', max_length=100),
        ),
    ]
