# Generated by Django 3.2.8 on 2022-03-23 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_alumno_alergico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(max_length=100)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.FileField(upload_to='guias')),
            ],
        ),
    ]
