# Generated by Django 3.2.8 on 2022-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='curso',
            field=models.CharField(default='sin curso', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='galeria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guia',
            name='cantidad',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
