# Generated by Django 3.2.8 on 2022-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0007_auto_20220328_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destacado',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='lead',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.CharField(default='SOME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tituloDestacado',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
