# Generated by Django 3.2.8 on 2022-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0008_auto_20220328_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='redactor',
            field=models.CharField(blank=True, default='Tomás Salgado', max_length=200, null=True),
        ),
    ]
