# Generated by Django 3.2.8 on 2022-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0009_alter_noticia_redactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='cantidad',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
    ]
