# Generated by Django 3.2.8 on 2022-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0010_alter_guia_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default='sin dirección', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fono',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(default='sin foto', upload_to='alumnos'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alergico',
            field=models.CharField(blank=True, default='no es alergico', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
