# Generated by Django 3.2.8 on 2022-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0011_auto_20220404_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, default='sin foto', null=True, upload_to='alumnos'),
        ),
    ]
