# Generated by Django 3.2.8 on 2022-04-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0012_alter_alumno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='foto',
        ),
    ]
