# Generated by Django 3.2.8 on 2022-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0013_remove_alumno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='password',
            field=models.CharField(default='altascumbres', max_length=100),
        ),
    ]
