# Generated by Django 3.2.8 on 2022-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0014_profesor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fechaIncorporacion',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(default='chilena', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='procedencia',
            field=models.CharField(default='Arcoiris', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='puebloOriginario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='reprobado',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
