# Generated by Django 3.2.8 on 2022-04-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0015_auto_20220407_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
    ]
