# Generated by Django 3.2.8 on 2022-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0016_remove_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
