# Generated by Django 3.2.8 on 2022-04-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0018_curso_profesorjefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='colegio.curso'),
            preserve_default=False,
        ),
    ]
