# Generated by Django 3.2.8 on 2022-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0024_auto_20220411_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(default='masculino', max_length=100),
        ),
    ]
