# Generated by Django 3.2.8 on 2022-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0025_alumno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
