# Generated by Django 3.2.8 on 2022-04-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0026_alumno_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fechaNacimiento',
        ),
    ]
