# Generated by Django 3.2.8 on 2022-04-13 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0027_remove_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
