# Generated by Django 3.2.8 on 2022-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0028_alumno_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='lead',
        ),
    ]
