# Generated by Django 3.2.8 on 2022-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0029_remove_noticia_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
