# Generated by Django 3.2.8 on 2022-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0030_alter_noticia_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaIncorporacion',
            field=models.DateTimeField(default=' ', max_length=100),
        ),
    ]
