# Generated by Django 3.2.8 on 2022-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0031_alter_alumno_fechaincorporacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alergico',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaIncorporacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='procedencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='reprobado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='rut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=100),
        ),
    ]
