# Generated by Django 3.2.8 on 2022-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0033_auto_20220421_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
