# Generated by Django 3.2.8 on 2022-04-21 11:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0036_alumno_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alergico',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='colegio.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaIncorporacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
