# Generated by Django 3.2.8 on 2022-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0038_alter_alumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='noticia',
            field=models.BooleanField(default=True),
        ),
    ]
