# Generated by Django 3.2.8 on 2022-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0040_remove_noticia_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=100)),
                ('bloque', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='colegio',
            field=models.BooleanField(default=True),
        ),
    ]
