# Generated by Django 3.2.8 on 2022-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0041_auto_20220505_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='colegio',
        ),
    ]
