# Generated by Django 3.2.8 on 2022-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0042_remove_noticia_colegio'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='noticia',
            field=models.BooleanField(default=True),
        ),
    ]
