# Generated by Django 3.2.8 on 2022-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0043_noticia_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('comunicado', models.CharField(max_length=200)),
                ('archivos', models.FileField(blank=True, null=True, upload_to='comunicados')),
            ],
        ),
    ]
