# Generated by Django 3.2.8 on 2022-05-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0046_alter_archivoscomunicado_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='comunicado',
            new_name='texto',
        ),
    ]
