# Generated by Django 3.2.8 on 2022-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0049_alter_comunicado_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
