# Generated by Django 3.2.8 on 2022-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0051_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='tema',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
