# Generated by Django 3.2.8 on 2022-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0052_auto_20220601_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, upload_to='libros'),
        ),
    ]
