# Generated by Django 3.2.8 on 2022-06-16 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0054_rename_libro_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('estadoCivil', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('lugarTrabajo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('estadoCivil', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('lugarTrabajo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('estadoCivil', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('lugarTrabajo', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido',
            new_name='materno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fono',
        ),
        migrations.AddField(
            model_name='alumno',
            name='beca',
            field=models.CharField(blank=True, default='no posee', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='hermanos',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='paterno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pie',
            field=models.CharField(blank=True, default='no pertenece', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='religion',
            field=models.CharField(blank='True', max_length=200),
        ),
        migrations.AddField(
            model_name='alumno',
            name='socioeconomica',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nacionalidad',
            field=models.CharField(blank=True, default='chilena', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='procedencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='reprobado',
            field=models.CharField(blank='True', default='No', max_length=200),
        ),
    ]
