# Generated by Django 3.2.8 on 2022-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0057_auto_20220623_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='parentesco',
            field=models.CharField(default='padre', max_length=200),
        ),
    ]
