# Generated by Django 3.2.8 on 2022-06-23 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegio', '0064_alter_apoderado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
