# Generated by Django 3.2.8 on 2022-06-24 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colegio', '0065_alter_apoderado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='email',
        ),
        migrations.AddField(
            model_name='alumno',
            name='audicion',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='audifonos',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='enfermedades',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lentes',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='peso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='problema',
            field=models.CharField(blank=True, default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='salud',
            field=models.CharField(blank=True, default='AFP', max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sanguineo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='talla',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='vision',
            field=models.CharField(blank=True, default='normal', max_length=100),
        ),
        migrations.AddField(
            model_name='madre',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.alumno'),
        ),
    ]
