# Generated by Django 3.2.8 on 2022-06-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0066_auto_20220624_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apoderado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.apoderado'),
        ),
    ]
