# Generated by Django 3.2.8 on 2022-06-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0068_alter_alumno_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('trabajo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='madre',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.tutor'),
        ),
    ]
