# Generated by Django 3.2.8 on 2022-06-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0069_auto_20220625_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.madre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.padre'),
        ),
    ]
