# Generated by Django 3.0.1 on 2022-12-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0071_auto_20221212_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='idAmigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
