# Generated by Django 3.0.1 on 2022-12-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0072_amigo_idamigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='idAmigo',
        ),
        migrations.AddField(
            model_name='amigo',
            name='nombreAmigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
