# Generated by Django 3.0.1 on 2022-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0073_auto_20221213_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='visto',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
