# Generated by Django 3.0.1 on 2022-12-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0074_amigo_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
