# Generated by Django 3.0.1 on 2023-03-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0075_amigo_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alumno', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
    ]
