# Generated by Django 3.0.1 on 2023-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0078_auto_20230328_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='taller',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='talleres',
            field=models.ManyToManyField(to='colegio.Taller'),
        ),
    ]
