# Generated by Django 3.0.1 on 2023-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0079_auto_20230328_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evaluaciones')),
            ],
        ),
    ]
