# Generated by Django 3.0.1 on 2023-03-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0080_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='archivo',
            field=models.FileField(default='null', upload_to='evaluaciones'),
        ),
    ]
