# Generated by Django 3.0.1 on 2023-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0084_remove_tenista_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenista',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
