# Generated by Django 3.0.1 on 2023-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0085_tenista_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenista',
            name='torneos',
            field=models.IntegerField(default=0),
        ),
    ]
