# Generated by Django 3.0.1 on 2023-04-12 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0086_tenista_torneos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(default='null', upload_to='boletines')),
                ('autor', models.CharField(default='Tomas Salgado', max_length=100)),
            ],
        ),
    ]
